services:
  quarto2pdf:
    build: .
    container_name: quarto2pdf
    restart: unless-stopped
    shm_size: "2gb"
    deploy:
      resources:
        limits:
          memory: 2g
    ports:
      - "8504:8504"
    environment:
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8504
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium